version: '2'
services:
    sgapp-mysql:
        container_name: sgapp-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/sgApp/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=sgapp
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
